[build.environment]
  TZ="Australia/Sydney"

[[redirects]]
  from = "/gigs.html"
  to = "/gig-guide"
  status = 301

[[redirects]]
  from = "/party"
  to = "https://events.humanitix.com/sydneymusic-net-merch-launch-and-fundraiser"
  status = 301

[[redirects]]
  from = "/bayang"
  to = "https://sydneymusic.net/reads/believe-in-your-shit-a-big-chat-with-bayang-tha-bushranger"
  status = 301

[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/script.outbound-links.tagged-events.js"
  status = 200

[[redirects]]
  from = "/contribute"
  to = "/reads/sydney-music-reads-call-for-contributors"
  status = 301

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200

[[redirects]]
  from = "/survey"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSe09CMW4ZGNdKuPt1O8nG0iWFj1St_6DNKvDqS7Rm4WqgjdOg/viewform"
  status = 301

[[redirects]]
  from = "/newsletter"
  to = "https://sydneymusic.us17.list-manage.com/subscribe?u=33fe15202bc9075111c10636a&id=08cf9e0f0b"
  status = 301

[[redirects]]
  from = "/discussion"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSeqvBq381rDhQFPHIDQIR7DCBKrAqKFFesZfU2PIBgQcwa9rg/viewform"
  status = 301

[[redirects]]
  from = "/viewsource"
  to = "https://github.com/sydneymusic-joe/sydneymusic"
  status = 301